FROM opensips/opensips:3.4

RUN apt update && apt install -y \
    opensips \
    opensips-cli \
    opensips-mysql-module \
    opensips-auth-modules \
    default-mysql-client \
    nano

CMD ["/usr/sbin/opensips", "-F"]
